DEFAULT_TIMEOUT = 15
DEFAULT_DURATION = 5

SNAP_IMAGE_DIMENSIONS = (1334, 750)

MEDIA_TYPE_UNKNOWN = -1
MEDIA_TYPE_IMAGE = 0
MEDIA_TYPE_VIDEO = 1
MEDIA_TYPE_VIDEO_NO_AUDIO= 2

FRIEND_CONFIRMED = 0
FRIEND_UNCONFIRMED = 1
FRIEND_BLOCKED = 2
PRIVACY_EVERYONE = 0
PRIVACY_FRIENDS = 1